# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f29769c15f64ff269b84367672c385ac83308897d5481d52cef8a2db3138b765c9e814242edfe624d5ab849e7e3d0b4e6d8e3bb96ffc20490154c87a4d485f6d

test:
  secret_key_base: d61427b2fddd4689dfbe74c84d96e08b9001cf2718f81783cad8f3fc54fdd44fa319132140ae43d4fb2122557e92495b066e2ee738d1c695d473151545a9e9d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
